TrainingMVC/TrainingMVC/Controllers/FormationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TrainingMVC.DATA;

namespace TrainingMVC.Controllers
{
    public class FormationController : Controller
    {
        private AvisFormationsEntities db = new AvisFormationsEntities();
        // GET: Formation
        public ActionResult Index()
        {
            var formations = db.Formation.ToList();
            ViewBag.formationName = "";
            return View(formations);
        }

        [HttpPost]
        public ActionResult Index(String formationName)
        {
            ViewBag.formationName = formationName;

            var formations = (formationName.Length > 0)
                ? db.Formation.Where(x => x.Nom.ToLower().Contains(formationName.ToLower())).ToList()
                : db.Formation.ToList();
                

            return View(formations);
        }


        // GET: Formation/Details/5
        public ActionResult Details(int id)
        {
            if (id.Equals(0))
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);    


            //var selectedFormation = db.Formation.Find(id);
            var selectedFormation = db.Formation.Where(x => x.Id == id).FirstOrDefault();

            if (selectedFormation == null)
                return HttpNotFound();


            return View(selectedFormation);
        }

        // GET: Formation/Create
        public ActionResult Create()
        {
            var newFormation = new Formation();
            return View(newFormation);
        }

        // POST: Formation/Create
        [HttpPost]
        public ActionResult Create(Formation newFormation)
        {
            try
            {
                if (ModelState.IsValid) { 

                    db.Formation.Add(newFormation);
                    db.SaveChanges();
                    // TODO: Add insert logic here

                    return RedirectToAction("Index");
                
                }

                return View(newFormation);

            }
            catch
            {
                return View(newFormation);
            }
        }

        // GET: Formation/Edit/5
        public ActionResult Edit(int id)
        {
            if (id.Equals(0))
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);


            //var selectedFormation = db.Formation.Find(id);
            var selectedFormation = db.Formation.Where(x => x.Id == id).FirstOrDefault();

            if (selectedFormation == null)
                return HttpNotFound();


            return View("editformation", selectedFormation);
        }

        // POST: Formation/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Formation selectedFormation)
        {
            try
            {
                db.Entry(selectedFormation).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Formation/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Formation/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

TrainingMVC/TrainingMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color : orange">
        @Html.ActionLink("Nom d'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">@Html.ActionLink("Accueil", "Index", "Home", new { @class = "nav-link active" })</li>
                <li class="nav-item">@Html.ActionLink("À propos de", "About", "Home", new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Contact", "Contact", "Home", new { @class = "nav-link" })</li>
                <li class="nav-item">@Html.ActionLink("Toutes-les-formations", "Index", "Formation", new { @class = "nav-link" })</li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Formation")" class="nav-link" >Formation </a>
                </li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>

    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>